### ISSUE TITLE
Error running plugin on android

### ISSUE THREAD

**Issue by nathanblanchard12** [tplkn/midi_player#1]
E/flutter (): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: MissingPluginException(No implementation found for method play_note on channel midi_player)
E/flutter (): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:165:7)
E/flutter (): <asynchronous suspension>

I got this error on android.

**Comment by tplkn** [comment]
@nathanblanchard12 Are you sure you restarted the app after adding the plugin? I cannot reproduce the bug, but it looks like you need to restart the app (not hot reload).
If you did restart and the bug still exists please provide
- output `flutter doctor -v`
- minimum code for reproduction if needed

**Comment by nathanblanchard12** [comment]
This is the error messages I am getting:
D/EGL_emulation( 7639): app_time_stats: avg=1286.08ms min=15.87ms max=4269.66ms count=4
D/EGL_emulation( 7639): app_time_stats: avg=9663.89ms min=9663.89ms max=9663.89ms count=1
I/flutter ( 7639): dev message
I/flutter ( 7639): MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences_android)
I/flutter ( 7639): platform android
I/flutter ( 7639): 5
D/EGL_emulation( 7639): app_time_stats: avg=288.38ms min=8.21ms max=860.37ms count=5
D/EGL_emulation( 7639): app_time_stats: avg=2852.70ms min=24.34ms max=8507.15ms count=3
I/flutter ( 7639): dev message
I/flutter ( 7639): MissingPluginException(No implementation found for method getTemporaryDirectory on channel plugins.flutter.io/path_provider_android)
D/EGL_emulation( 7639): app_time_stats: avg=810.57ms min=22.53ms max=1908.62ms count=3
I/flutter ( 7639): difference 0.3127   newPrice 125.08  noteToPlay 6 percentage 0.0 range : 0.0025 , percentage 0.0
I/flutter ( 7639): FormatException: Invalid double
I/flutter ( 7639): dev message
I/flutter ( 7639): MissingPluginException(No implementation found for method getTemporaryDirectory on channel plugins.flutter.io/path_provider_android)
I/flutter ( 7639): difference 0.3127   newPrice 124.28  noteToPlay 6 percentage 0.0 range : 0.0025 , percentage 0.0
I/flutter ( 7639): FormatException: Invalid double
I/flutter ( 7639): dev message
I/flutter ( 7639): MissingPluginException(No implementation found for method getTemporaryDirectory on channel plugins.flutter.io/path_provider_android)
I/flutter ( 7639): difference 0.3127   newPrice 124.68  noteToPlay 6 percentage 0.0 range : 0.0025 , percentage 0.0
I/flutter ( 7639): FormatException: Invalid double
I/flutter ( 7639): dev message
I/flutter ( 7639): MissingPluginException(No implementation found for method getTemporaryDirectory on channel plugins.flutter.io/path_provider_android)
D/EGL_emulation( 7639): app_time_stats: avg=4094.53ms min=4094.53ms max=4094.53ms count=1

**Comment by tplkn** [comment]
Looks like you have a lot of problems with plugins. Check your flutter version and `flutter pub get` output. It's not [midi_player](https://github.com/tplkn/midi_player) problem.
